#!/usr/bin/env bash
# -*- mode: shell-script; sh-shell: bash; -*-
# Copyright (c) 2023 Peter Morgan <peter.james.morgan@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


TEMP_DIR=$(mktemp -d)

git -C "$TEMP_DIR" init
echo "hello world" > "$TEMP_DIR/greeting.txt"
git -C "$TEMP_DIR" add greeting.txt
git -C "$TEMP_DIR" commit -m "initial"
git -C "$TEMP_DIR" remote add origin ssh://localhost:22022/$(basename "$TEMP_DIR")
git -C "$TEMP_DIR" push --set-upstream origin main
