---
on:
  push:
    branches:
      - main
      - develop
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
env:
  REGISTRY: 'ghcr.io'
jobs:
  package:
    permissions:
      packages: write
    strategy:
      matrix:
        erlang:
          - "26.0.2"
        rust:
          - "1.70.0"
    runs-on: ubuntu-latest
    outputs:
      image: ${{steps.bdra.outputs.image}}
      tags: ${{steps.bdra.outputs.tags}}
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.erlang}}
      - run: make distclean all
      - uses: shortishly/beam-docker-release-action@main
        id: bdra
        with:
          registry: ${{env.REGISTRY}}
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
          build-image: ghcr.io/shortishly/erlang-rust:${{matrix.erlang}}-${{matrix.rust}}
          build-command: make distclean all
          build-platforms: linux/amd64,linux/arm64
          image-description: >-
            shrugs is a git server that you can push, clone or pull
            over ssh... ¯\_(ツ)_/¯
          image-licenses: Apache-2.0
  smoke-test:
    needs: package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: >-
          docker compose
          up
          --detach
          --remove-orphans
        env:
          SHRUGS_IMAGE: ${{needs.package.outputs.image}}
          SHRUGS_VERSION: ${{needs.package.outputs.tags}}
      - run: |
          sudo apt-get update
          sudo apt-get install -y bats openssh-client
      - run: |
          sleep 60
      - run: |
          which ssh-keygen
          which ssh
          which docker
          ssh-keygen -t ed25519 -N '' -f "$KEY" -C "bob@example.com"
          docker compose cp "$KEY.pub" shrugs:/users
          ssh -o UserKnownHostsFile=/dev/null -o IdentityFile="$KEY" -o StrictHostKeyChecking=no -p 22022 localhost auth_key_comments
        env:
          KEY: bob
