---
on:
  push:
    branches:
      - main
      - develop
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
env:
  REGISTRY: 'ghcr.io'
permissions:
  packages: write
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        erlang: ["25.3.2"]
        rust: ["1.68.2"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.erlang}}
      - name: Build
        run: make distclean all
      - name: Beam Docker Release
        uses: shortishly/beam-docker-release-action@main
        with:
          registry: ${{env.REGISTRY}}
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
          build-image: ghcr.io/shortishly/erlang-rust:${{matrix.erlang}}-${{matrix.rust}}
          build-command: make distclean all
          build-platforms: linux/amd64,linux/arm64
          image-description: >-
            shrugs is a git server that you can push, clone or pull
            over ssh... ¯\_(ツ)_/¯
          image-licenses: Apache-2.0
