---
on:
  pull_request:
  workflow_dispatch:
jobs:
  build:
    name: build, dialyze and test
    strategy:
      matrix:
        erlang:
          - 26.1.2
        rust:
          - 1.74.0
        os:
          - ubuntu-latest
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.erlang}}
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy, rustfmt
          toolchain: ${{matrix.rust}}
      - run: make all dialyze tests
